# numpy math operations

In [1]:
a = [1,2,3]
b = [4,5,6]

a + b

[1, 2, 3, 4, 5, 6]

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [9]:
print(type(a + b))

<class 'numpy.ndarray'>


In [ ]:
print(a + b)

In [7]:
print(a-b)
print(a*b)
print(a/b)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# comparison

print(a > b)
print(a < b)
print(a == b)

<class 'numpy.ndarray'>
[ True  True  True]
[False False False]


In [15]:
ans = a > b
print(type(ans[0]))

<class 'numpy.bool'>


In [20]:
# logical operators

# and , or , not

x = np.array([True, False, True])
y = np.array([False, False, True])

print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))

[False False  True]
[ True False  True]
[False  True False]


In [22]:
# biwsise operators

a = np.array([1, 2, 3])
b = np.array([0, 1, 1])

print(np.bitwise_and(a,b))
print(np.bitwise_or(a,b))

[0 0 1]
[1 3 3]


In [26]:
# modulus and power

a = np.array([10, 20, 30])
b = np.array([3, 7, 4])

print(np.mod(a, b))
print(np.power(a, b))


[1 6 2]
[      1000 1280000000     810000]
